import { applications, esc, icon } from "./shared.js";

/** Inquiry markup retained from the approved single-file prototype. */
export function createInquiryTemplates(state, shared) {
  const { cart = [], draft = {}, lastBrief = null } = state;
  const { breadcrumb, countries, inquirySummary, briefText } = shared;
  function renderInquiry() {
    return `<header class="page-header"><div class="page-header-inner">${breadcrumb([["Quotation brief"]])}<p class="eyebrow blue-text">LET’S MAKE THE REQUIREMENTS CLEAR</p><h1>Your next range starts here.</h1><p>Tell us who you are sourcing for, where the products will go and what matters to your purchase.</p></div></header><div class="inquiry-layout"><form id="inquiry-form" class="inquiry-form"><h2>Tell us about your business.</h2><p>Your product list and requirements will be combined in one brief.</p><div class="form-grid"><label class="field">Company name *<input name="company" autocomplete="organization" maxlength="150" required value="${esc(draft.company || "")}" placeholder="Your company"></label><label class="field">Contact name *<input name="contact" autocomplete="name" maxlength="100" required value="${esc(draft.contact || "")}" placeholder="Full name"></label><label class="field">Business email *<input name="email" type="email" autocomplete="email" required maxlength="150" value="${esc(draft.email || "")}" placeholder="you@company.com"></label><label class="field">Country / region *<select name="country" required>${countries(draft.country)}</select></label><label class="field full-width" id="other-country-field" ${draft.country === "Other" ? "" : "hidden"}>Destination country *<input name="otherCountry" value="${esc(draft.otherCountry || "")}" ${draft.country === "Other" ? "required" : ""} maxlength="100" placeholder="Your destination country"></label><label class="field">I am sourcing as<select name="role">${["Distributor / wholesaler", "Private-label brand", "Project / installation company", "Retailer / e-commerce seller", "Other business"].map((x) => `<option ${draft.role === x ? "selected" : ""}>${x}</option>`).join("")}</select></label><label class="field">Application<select name="application"><option value="">Product range / multiple applications</option>${Object.entries(
      applications,
    )
      .map(
        ([id, a]) =>
          `<option value="${id}" ${draft.application === id ? "selected" : ""}>${a.label}</option>`,
      )
      .join(
        "",
      )}</select></label><label class="field">Target timing<input name="timing" value="${esc(draft.timing || "")}" maxlength="100" placeholder="e.g. Samples first, order after approval"></label><label class="field">Phone / WhatsApp (optional)<input name="phone" autocomplete="tel" type="tel" maxlength="60" value="${esc(draft.phone || "")}" placeholder="Country code + number"></label><label class="field full-width">Your requirements ${cart.length ? "" : "*"}<textarea name="message" maxlength="6000" ${cart.length ? "" : "required"} placeholder="Product configuration, target quantity, site dimensions, operating needs, branding or documents…">${esc(draft.message || "")}</textarea></label><label class="upload-field full-width">Site photos or plans (optional)<small class="muted" style="display:block">File names are recorded in the brief; files are not uploaded or bundled.</small><input type="file" name="attachments" accept="image/*,.pdf" multiple></label></div><div class="inline-info">${icon("info")}<span>Preview mode: your brief is saved locally and can be downloaded. It is not sent to a sales inbox. Attach the source files when you share the exported brief.</span></div><label class="checkbox-field"><input type="checkbox" name="consent" required> <span>I agree to save these details in this browser and include them in my downloadable inquiry brief.</span></label><button class="btn btn-amber" type="submit">Prepare my inquiry brief ${icon("arrow-right")}</button><button class="text-button" type="button" data-action="save-draft" style="margin-left:20px">Save draft</button><button class="text-button" type="button" data-action="clear-draft" style="margin-left:20px">Clear saved details</button></form>${inquirySummary()}</div>`;
  }
  function renderSuccess() {
    if (!lastBrief) return renderInquiry();
    return `<section class="success-card">${icon("circle-check")}<p class="eyebrow blue-text">READY TO REVIEW & SHARE</p><h1>Your inquiry brief is ready.</h1><p>Your selected products and requirements are together in one file. Download it for review and sharing. This preview has not sent an inquiry.</p><div class="success-actions"><button class="btn btn-blue" data-action="download-brief">${icon("download")}Download brief (TXT)</button><button class="btn btn-outline" data-action="download-json">Download JSON</button><button class="btn btn-outline" data-action="edit-brief">Edit brief</button></div><pre>${esc(briefText(lastBrief))}</pre><a class="text-link" href="#/products">Continue exploring products ${icon("arrow-right")}</a></section>`;
  }
  return { renderInquiry, renderSuccess };
}
